## Deployment for Testing Vault K8s Auth
# sed -e "s/dbfa0f/$dbfa0f_PLATE/g" -e "s/clab/$clab_NAME/g" -e "s/nonprod/$nonprod/g" -e "s/dev/$dev/g" deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vault-test
  namespace: dbfa0f-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault-test
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-helloworld: dbfa0f-nonprod/helloworld
        # note this is required to use the lab vault instance as the injector in lab does not have this configured
        vault.hashicorp.com/service: https://vault-lab.developer.gov.bc.ca
        vault.hashicorp.com/agent-inject-template-helloworld: |
          {{- with secret "dbfa0f-nonprod/helloworld" }}
          {{ .Data.data.hello }}
          {{ end }}
        vault.hashicorp.com/agent-inject-token: 'true'
        vault.hashicorp.com/auth-path: auth/k8s-clab
        vault.hashicorp.com/namespace: platform-services
        vault.hashicorp.com/role: dbfa0f-nonprod
    spec:
      containers:
        - name: vault
          image: 'docker.io/hashicorp/vault:1.8.3'
          command:
            - /bin/sh
          args:
            - '-c'
            - while true; do cat /vault/secrets/helloworld; sleep 10; done
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: dbfa0f-vault
      serviceAccount: dbfa0f-vault
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600