# GitOpsTeam - create this CRD in your tools namespace in order to enable
# Argo CD for your project
apiVersion: warden.devops.gov.bc.ca/v1alpha1
kind: GitOpsTeam
metadata:
  name: gitopsteam-myproject
  namespace: myproject-tools
spec:
  # gitOpsMembers defines the git repo access (tenant-gitops-XYZ)
  # Note that users with repo access will have to accept an invitation from 
  # GitHub to join the bcgov-c GitHub organization if they are not already 
  # members.
  #
  # Note: 
  #   You may include IDIR email addresses (UPN) for IDIR-based access
  #   GitHub IDs are CASE SENSITIVE
  #   Do not append "@github" to GitHub IDs
  # -----------------------------------------------------------------------
  gitOpsMembers:

    # Full admin access to the repo, including repo deletion, adding of users
    # Recommended for people who need full access to the project, including
    # sensitive and destructive actions like managing security or deleting a
    # repository.
    admins:
      - myCaseSensitiveGitHubID

    # Recommended for contributors who actively push to your project.
    writers:
      - dev1-githubid

    # Recommended for project managers who need to manage the repository without
    # access to sensitive or destructive actions.
    maintainers:

    # Recommended for non-code contributors who want to view or discuss your
    # project.
    readers:

    # Recommended for contributors who need to manage issues and pull requests
    # without write access.
    triage:

  # projectMembers defines access to the Argo CD UI
  #
  # Note:
  #   GitHub IDs must have "@github" appended to the ID
  #   You may include IDIR email addresses (UPN) for IDIR-based access
  #   GitHub IDs are not case sensitive in this section
  # ------------------------------------------------------------------
  projectMembers:

    # Project Maintainers have full access to the Argo CD Project, including the
    # ability create, edit, and delete Applications within the Project
    maintainers:
      - myGitHubID@github

    # Project Readers have read-only access to the Project in the Argo CD UI
    readers:
